---

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https

- name: Install APT key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - filebeat

- name: Enable service
  ansible.builtin.service:
    name: filebeat
    state: started
    enabled: yes

- name: Write configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ filebeat.config_files }}"
  notify:
    - filebeat

- name: Enable nginx module
  ansible.builtin.shell:
    cmd: "filebeat modules enable nginx"
  notify:
    - filebeat

- name: copy the modsecurity2 module to remote
  ansible.builtin.copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ filebeat.modules }}"
  notify:
    - filebeat
  when: filebeat.modules is defined








